package modelo;
// Generated 07-may-2024 20:51:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private int id;
     private Factura factura;
     private Historial historial;
     private Receta receta;
     private Tratamiento tratamiento;
     private Veterinario veterinario;
     private Date fecha;
     private Date hora;
     private String motivo;
     private Set facturas = new HashSet(0);
     private Set recetas = new HashSet(0);
     private Set tratamientos = new HashSet(0);

    public Cita() {
    }

    public Cita(int id, Historial historial, Veterinario veterinario, Date fecha, Date hora, String motivo) {
        this.id = id;
        this.historial = historial;
        this.veterinario = veterinario;
        this.fecha = fecha;
        this.hora = hora;
        this.motivo = motivo;
    }
    
    public Cita(int id, Factura factura, Historial historial, Receta receta, Tratamiento tratamiento, Veterinario veterinario, Date fecha, Date hora, String motivo, Set facturas, Set recetas, Set tratamientos) {
       this.id = id;
       this.factura = factura;
       this.historial = historial;
       this.receta = receta;
       this.tratamiento = tratamiento;
       this.veterinario = veterinario;
       this.fecha = fecha;
       this.hora = hora;
       this.motivo = motivo;
       this.facturas = facturas;
       this.recetas = recetas;
       this.tratamientos = tratamientos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Historial getHistorial() {
        return this.historial;
    }
    
    public void setHistorial(Historial historial) {
        this.historial = historial;
    }
    public Receta getReceta() {
        return this.receta;
    }
    
    public void setReceta(Receta receta) {
        this.receta = receta;
    }
    public Tratamiento getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(Tratamiento tratamiento) {
        this.tratamiento = tratamiento;
    }
    public Veterinario getVeterinario() {
        return this.veterinario;
    }
    
    public void setVeterinario(Veterinario veterinario) {
        this.veterinario = veterinario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getRecetas() {
        return this.recetas;
    }
    
    public void setRecetas(Set recetas) {
        this.recetas = recetas;
    }
    public Set getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Set tratamientos) {
        this.tratamientos = tratamientos;
    }




}


