package modelo;
// Generated 27-abr-2024 18:08:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private Integer id;
     private Date fecha;
     private Date hora;
     private String motivo;
     private int numHistorial;
     private int idVeterinario;
     private Integer idTratamiento;
     private Integer idReceta;
     private int idFactura;

    public Cita() {
    }

	
    public Cita(Date fecha, Date hora, String motivo, int numHistorial, int idVeterinario, int idFactura) {
        this.fecha = fecha;
        this.hora = hora;
        this.motivo = motivo;
        this.numHistorial = numHistorial;
        this.idVeterinario = idVeterinario;
        this.idFactura = idFactura;
    }
    public Cita(Date fecha, Date hora, String motivo, int numHistorial, int idVeterinario, Integer idTratamiento, Integer idReceta, int idFactura) {
       this.fecha = fecha;
       this.hora = hora;
       this.motivo = motivo;
       this.numHistorial = numHistorial;
       this.idVeterinario = idVeterinario;
       this.idTratamiento = idTratamiento;
       this.idReceta = idReceta;
       this.idFactura = idFactura;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public int getNumHistorial() {
        return this.numHistorial;
    }
    
    public void setNumHistorial(int numHistorial) {
        this.numHistorial = numHistorial;
    }
    public int getIdVeterinario() {
        return this.idVeterinario;
    }
    
    public void setIdVeterinario(int idVeterinario) {
        this.idVeterinario = idVeterinario;
    }
    public Integer getIdTratamiento() {
        return this.idTratamiento;
    }
    
    public void setIdTratamiento(Integer idTratamiento) {
        this.idTratamiento = idTratamiento;
    }
    public Integer getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(Integer idReceta) {
        this.idReceta = idReceta;
    }
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }




}


