package modelo;
// Generated 03-may-2024 14:34:39 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Integer id;
     private int idPaciente;

    public Historial() {
    }

    public Historial(int idPaciente) {
       this.idPaciente = idPaciente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(int idPaciente) {
        this.idPaciente = idPaciente;
    }




}


