package modelo;
// Generated 07-may-2024 20:51:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Medicamento generated by hbm2java
 */
public class Medicamento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Date fechaCaducidad;

    public Medicamento() {
    }

    public Medicamento(String nombre, Date fechaCaducidad) {
       this.nombre = nombre;
       this.fechaCaducidad = fechaCaducidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }




}


