package modelo;
// Generated 23-may-2024 19:10:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicamento generated by hbm2java
 */
public class Medicamento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Date fechaCaducidad;
     private Set citas = new HashSet(0);

    public Medicamento() {
    }

	
    public Medicamento(String nombre, Date fechaCaducidad) {
        this.nombre = nombre;
        this.fechaCaducidad = fechaCaducidad;
    }
    public Medicamento(String nombre, Date fechaCaducidad, Set citas) {
       this.nombre = nombre;
       this.fechaCaducidad = fechaCaducidad;
       this.citas = citas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


