package modelo;
// Generated 27-abr-2024 18:08:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String especie;
     private String raza;
     private String sexo;
     private int edad;
     private Date fechaNacimiento;
     private int idPropietario;
     private int numHistorial;

    public Paciente() {
    }

    public Paciente(String nombre, String especie, String raza, String sexo, int edad, Date fechaNacimiento, int idPropietario, int numHistorial) {
       this.nombre = nombre;
       this.especie = especie;
       this.raza = raza;
       this.sexo = sexo;
       this.edad = edad;
       this.fechaNacimiento = fechaNacimiento;
       this.idPropietario = idPropietario;
       this.numHistorial = numHistorial;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(String especie) {
        this.especie = especie;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getIdPropietario() {
        return this.idPropietario;
    }
    
    public void setIdPropietario(int idPropietario) {
        this.idPropietario = idPropietario;
    }
    public int getNumHistorial() {
        return this.numHistorial;
    }
    
    public void setNumHistorial(int numHistorial) {
        this.numHistorial = numHistorial;
    }




}


