package modelo;
// Generated 23-may-2024 19:10:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer id;
     private Propietario propietario;
     private String nombre;
     private String especie;
     private String raza;
     private String sexo;
     private int edad;
     private Date fechaNacimiento;
     private Set historials = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(Propietario propietario, String nombre, String especie, String raza, String sexo, int edad, Date fechaNacimiento) {
        this.propietario = propietario;
        this.nombre = nombre;
        this.especie = especie;
        this.raza = raza;
        this.sexo = sexo;
        this.edad = edad;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Paciente(Propietario propietario, String nombre, String especie, String raza, String sexo, int edad, Date fechaNacimiento, Set historials) {
       this.propietario = propietario;
       this.nombre = nombre;
       this.especie = especie;
       this.raza = raza;
       this.sexo = sexo;
       this.edad = edad;
       this.fechaNacimiento = fechaNacimiento;
       this.historials = historials;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propietario getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(String especie) {
        this.especie = especie;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }




}


