package modelo;
// Generated 29-may-2024 18:20:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Propietario generated by hbm2java
 */
public class Propietario  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String direccion;
     private int telefono;
     private String correo;
     private String infoContactoAdicional;
     private String password;
     private Set facturas = new HashSet(0);
     private Set pacientes = new HashSet(0);

    public Propietario() {
    }

	
    public Propietario(String dni, String nombre, String direccion, int telefono, String correo, String infoContactoAdicional, String password) {
        this.dni = dni;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.correo = correo;
        this.infoContactoAdicional = infoContactoAdicional;
        this.password = password;
    }
    public Propietario(String dni, String nombre, String direccion, int telefono, String correo, String infoContactoAdicional, String password, Set facturas, Set pacientes) {
       this.dni = dni;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.infoContactoAdicional = infoContactoAdicional;
       this.password = password;
       this.facturas = facturas;
       this.pacientes = pacientes;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getInfoContactoAdicional() {
        return this.infoContactoAdicional;
    }
    
    public void setInfoContactoAdicional(String infoContactoAdicional) {
        this.infoContactoAdicional = infoContactoAdicional;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }




}


