package modelo;
// Generated 22-may-2024 21:09:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Receta generated by hbm2java
 */
public class Receta  implements java.io.Serializable {


     private Integer id;
     private String dosis;
     private String indicaciones;
     private Set citas = new HashSet(0);

    public Receta() {
    }

	
    public Receta(String dosis, String indicaciones) {
        this.dosis = dosis;
        this.indicaciones = indicaciones;
    }
    public Receta(String dosis, String indicaciones, Set citas) {
       this.dosis = dosis;
       this.indicaciones = indicaciones;
       this.citas = citas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDosis() {
        return this.dosis;
    }
    
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }
    public String getIndicaciones() {
        return this.indicaciones;
    }
    
    public void setIndicaciones(String indicaciones) {
        this.indicaciones = indicaciones;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


