package modelo;
// Generated 26-abr-2024 11:41:48 by Hibernate Tools 4.3.1



/**
 * Receta generated by hbm2java
 */
public class Receta  implements java.io.Serializable {


     private Integer id;
     private String dosis;
     private String indicaciones;
     private int idCita;

    public Receta() {
    }

    public Receta(String dosis, String indicaciones, int idCita) {
       this.dosis = dosis;
       this.indicaciones = indicaciones;
       this.idCita = idCita;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDosis() {
        return this.dosis;
    }
    
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }
    public String getIndicaciones() {
        return this.indicaciones;
    }
    
    public void setIndicaciones(String indicaciones) {
        this.indicaciones = indicaciones;
    }
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }




}


