package modelo;
// Generated 07-may-2024 20:51:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento  implements java.io.Serializable {


     private int id;
     private Cita cita;
     private String tipo;
     private Date fecha;
     private double precio;
     private String resultados;
     private Set citas = new HashSet(0);

    public Tratamiento() {
    }

	
    public Tratamiento(int id, Cita cita, String tipo, Date fecha, double precio, String resultados) {
        this.id = id;
        this.cita = cita;
        this.tipo = tipo;
        this.fecha = fecha;
        this.precio = precio;
        this.resultados = resultados;
    }
    public Tratamiento(int id, Cita cita, String tipo, Date fecha, double precio, String resultados, Set citas) {
       this.id = id;
       this.cita = cita;
       this.tipo = tipo;
       this.fecha = fecha;
       this.precio = precio;
       this.resultados = resultados;
       this.citas = citas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public String getResultados() {
        return this.resultados;
    }
    
    public void setResultados(String resultados) {
        this.resultados = resultados;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


