package modelo;
// Generated 26-abr-2024 11:41:48 by Hibernate Tools 4.3.1



/**
 * Veterinario generated by hbm2java
 */
public class Veterinario  implements java.io.Serializable {

     private String nombre;
     private String especialidad;
     private int experiencia;
     private int telefono;
     private String correo;
     private String dni;

    public Veterinario() {
    }

    public Veterinario(String nombre, String especialidad, int experiencia, int telefono, String correo, String dni) {
       this.nombre = nombre;
       this.especialidad = especialidad;
       this.experiencia = experiencia;
       this.telefono = telefono;
       this.correo = correo;
       this.dni = dni;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public int getExperiencia() {
        return this.experiencia;
    }
    
    public void setExperiencia(int experiencia) {
        this.experiencia = experiencia;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }




}


